### ISSUE TITLE
Add a way to connect to other EOS chains

### ISSUE THREAD

**Issue by iamveritas** [Takafuly/mobeos#2]
currently there are a couple of other EOS chains
1. Enumivo
2. Telos
3. EOS testnet
4. other's will spin off for sure

it would be nice if would be a way to add other blockchains (by blockchain id, and APIs endpoints, and token symbols + corresponding contracts); I envision this as a section in settings/config json which can be read by the tool and a UI tab that allows for switching between chains.

**Comment by asghaier76** [comment]
Yes that is in the plan to be added in the next version.

**Comment by asghaier76** [comment]
Jungle Testnet and TELOS Testnet (limited) support were added
